### ISSUE TITLE
Team DJ+

### ISSUE THREAD

**Issue by jameslinjl** [ColumbiaJS/js-course#10]
We have two people so far, Danny (@khuumi) and James (@jameslinjl), on the team so far. We are looking for one or two more people to work on something (hence the +). Not sure what to work on yet, but we'll figure it out. We're both seniors, so we have a decent amount of coding experience, though not as much in JavaScript. Mac users preferable/mandatory.

**Comment by jzf2101** [comment]
Hey join our team on #9 !
