### ISSUE TITLE
Team Members Wanted: Dance DB (Solution to "WHO IS THE LEFT SHARK?")

### ISSUE THREAD

**Issue by njt2116** [ColumbiaJS/js-course#12]
Hey all --

I want to create a Wiki/LinkedIn/IMDB sort of site to allow professional dancers to input the jobs they have worked, and who worked on it with them....e.g.  
Maybe you could search to see which dancers danced for Missy Elliot on a specific tour, or WHO IS THE LEFT SHARK in Katy Perry's superbowl performance? And what other jobs did they do?
There is not a searchable site at this point tracking this info, and it would do a lot for the industry to build this!   For this class, maybe we could limit the scope to creating the profile pages and putting info into the database?

Experience: 
Have done some Database, Javascript, and Bootstrap style stuff in the past.

**Comment by annie** [comment]
Haha I love it, I'm down to join your team!

**Comment by njt2116** [comment]
Okay great, @azhang496! Welcome! We need to get some more people in here:) Will try to make it happen--let me know if you change your mind and end up in another group.  Look forward to meeting you!

**Comment by williamFalcon** [comment]
I'll join you guys!

**Comment by njt2116** [comment]
Awesome @williamFalcon!

**Comment by njt2116** [comment]
Hey @azhang496 and @williamFalcon , I'm going to close this issue and open a new one to search for any additional members.  I have created a repo and added the two of you (as well as Morris and Lev as per the assignment instructions.) Let me know if anything has changed!

**Comment by ghost** [comment]
@njt2116 @williamFalcon @azhang496  I'm not going to lie; I'm jealous of the name!  TOUCHE Team Left Shark, TOUCHE.
