### ISSUE TITLE
Looking for a team

### ISSUE THREAD

**Issue by ozzieba** [ColumbiaJS/js-course#13]
I'm a senior,  significant programming and data analysis experience but not much Web, have a Windows laptop and some Linux servers, not available to meet any Friday night to Saturday evening.

**Comment by ghost** [comment]
@ozzieba, If you haven't already gotten a team, you are welcome to join ours
[Team Dirt Off Your Shoulder](https://github.com/ColumbiaJS/js-course/issues/9)

**Comment by ozzieba** [comment]
Thanks @cev2107, I now have a team
