### ISSUE TITLE
Object function has no method split? Issue in hw2 cache.spec

### ISSUE THREAD

**Issue by jzf2101** [ColumbiaJS/js-course#15]
Is this a spec issue? I have this when I run gulp

```
Stack:
TypeError: Object function (arg1) {
      complexFunctionCalls++;
      return arg1.split('').reverse().join('');
    } has no method 'split'
    at Object.complexFunction (/Users/4d/Documents/js/w3101hws/hw2/lib/cache/cache.spec.js:16:19)
```

**Comment by levbrie** [comment]
@jzf2101 This is what the hint about `JSON.stringify()` is about.  You don't necessarily know what type of arguments you're going to be given.  If you're given a string, then you can call split on it, but if you're given an object or a function or something like that, that won't work. `JSON.stringify()` can turn an object, a function, or a whole set of arguments into a string.
