### ISSUE TITLE
Persistent "expected 'object' to equal 'function'" error in Event

### ISSUE THREAD

**Issue by blanksblanks** [ColumbiaJS/js-course#17]
I've tried <code>function Event() {
}</code>, <code>var Event = function Event() {
};</code>, <code>var Event = function { }</code> followed by <code>module.exports = Event;</code> at the end, and have also tried changing the name <code>Event</code> since I thought it might be reserved, but I keep getting the same message from mocha: expected 'object' to equal 'function'. 

However, when I <code>  console.log(Object.prototype.toString.call(Event));</code> and <code>console.log(typeof Event);</code> I get <code>[object Function]</code> and <code>function</code> as my Terminal output. Is there anything else I can try to ensure that <event> returns a function?

**Comment by levbrie** [comment]
@blanksblanks You need both the `module.exports` and the `function` statement.  The last example you have, `var Event = function { }` needs to have parentheses after the function keyword, so something like:

``` js
function Event() {

}

module.exports = Event;
```

Keep in mind that after you do this you will still be getting an error since you haven't yet implemented the subscribe(), unsubscribe(), or emit() methods, but this is the right setup.  Let me know if that helps, and please reopen if you still have questions.

**Comment by blanksblanks** [comment]
@levbrie I didn't include the rest of my code, but I believe I've implemented all the functions in this part of the assignment. My console is printing the right values for the methods I think - the problem is still that gulp keeps producing the same error about an object being returned instead of a function.

Currently this is how I declare Event:

<pre><code>  var Event = function Event() {
    // property declarations here
}</code></pre>

and what I have my console print out for testing is
<pre><code>
Event prototype: [object Function]
typeof Event: function
function (a, b) { return a + b; } subscribed!
[object Arguments] should emit
Result : 3
function (a, b) { return a + b; } unsubscribed
</pre></code>.

If I'm not descriptive enough, my Event.js has been pushed to my hw2 repo.

**Comment by blanksblanks** [comment]
I don't think I have the rights to re-open issues or add labels, sorry!

**Comment by levbrie** [comment]
Can you take a screenshot of your stacktrace and include it in this conversation?

**Comment by blanksblanks** [comment]
Thanks for reminding me to look more closely the stack - I should have noticed before, but the error is coming from cache.spec.js, not event.spec.js. For some reason when I change the <code>describe</code> line in event.spec.js to <code>describe.only</code>, gulpstill runs the checks on cache.js and doesn't get to event.js. If you have any tips for how I can check only event.js, that would be great! Otherwise we can close this issue - I'll just try to complete the other parts of the assignment before checking to see if my solution for the event part is valid. Thanks for the quick response!

![screen shot 2015-02-05 at 3 09 12 pm](https://cloud.githubusercontent.com/assets/7012294/6068331/35862588-ad49-11e4-9485-68abb2cf9542.png)

**Comment by levbrie** [comment]
@blanksblanks Good catch - that does seem to be the issue.  I've seen this a few times before - for some reason, before you actually have a module setup correctly - in this case cache.js - mocha will still throw assertion errors for this test.  It may have something to do with when required-in modules are evaluated.  I think that once you create a skeleton for cache.js with a basic function and a module.exports statement to export it, the describe.only will work correctly and it will go back to only running the event.spec.js tests, but you'll probably have to do this for the csv-analyzer files as well.  I think this behavior may be a bug in mocha.
