### ISSUE TITLE
Lev's sublime setup

### ISSUE THREAD

**Issue by guribe94** [ColumbiaJS/js-course#18]
If possible could we get a list of plugins/how to configure sublime to work the same way as Lev's does at some point?

**Comment by levbrie** [comment]
@guribe94 I'm working on this and hope to have it for everyone by Monday, if not sooner.

**Comment by levbrie** [comment]
@guribe94 I've added a page about my Sublime setup as well as links to my own customized color scheme and JavaScript snippets on the wiki at https://github.com/ColumbiaJS/js-course/wiki/Sublime-Text-3-Setup

**Comment by njt2116** [comment]
Awesome.  Thanks so much @levbrie --this is great!  The sidebar icons are very helpful for orienting myself in the MEAN layout.  Just what I was talking about at the end of the workshop!
