### ISSUE TITLE
Lookin' for team

### ISSUE THREAD

**Issue by ericdonahue** [ColumbiaJS/js-course#19]
Hi so I'm looking for a team to join. I'm an American Studies-majoring senior in The College™, not very experienced (just this class and 1004) but I more than make up for it with SPIRIT!

STATS
Full Name: Eric Michael Donahue
UNI: emd2163
Github name: ericdonahue

Don't have a project idea but I'm open to working on anything, with any framework I suppose (I'll be at the first workshop this weekend for sure). Thanks!

**Comment by jzf2101** [comment]
Join our team #9

On Feb 5, 2015, at 21:21, ericdonahue notifications@github.com wrote:

Hi so I'm looking for a team to join. I'm an American Studies-majoring
senior in The College™, not very experienced (just this class and 1004) but
I more than make up for it with SPIRIT!

STATS
Full Name: Eric Michael Donahue
UNI: emd2163
Github name: ericdonahue

Don't have a project idea but I'm open to working on anything, with any
framework I suppose (I'll be at the first workshop this weekend for sure).
Thanks!

—
Reply to this email directly or view it on GitHub
https://github.com/ColumbiaJS/js-course/issues/19.

**Comment by ghost** [comment]
@ericdonahue Eric, we'd love to have you on our team. I second @jzf2101

**Comment by annie** [comment]
Yo! We're also looking for a 4th team member if you're interested (#20).  It'd be cool to have another undergrad on our team too!
