### ISSUE TITLE
Code from class

### ISSUE THREAD

**Issue by jzf2101** [ColumbiaJS/js-course#2]
Could we also have code examples from class posted?

**Comment by levbrie** [comment]
Just posted the code examples from class - these are in the repo's hello-world/ directory.  Also make sure to take a look at the functions wiki page, in which I go through building a Calculator function step by step (you can see the tests for this in the hello-world/test/ directory).

**Comment by jzf2101** [comment]
Thanks!

On Jan 22, 2015, at 18:06, Lev Brie notifications@github.com wrote:

Closed #2 https://github.com/ColumbiaJS/js-course/issues/2.

—
Reply to this email directly or view it on GitHub
https://github.com/ColumbiaJS/js-course/issues/2#event-223378821.
