### ISSUE TITLE
Seeking Team

### ISSUE THREAD

**Issue by kingsykes** [ColumbiaJS/js-course#21]
I'm a moderately experienced, mostly self-taught programmer looking for a team to join.
I have loads of ideas, many related to ecommerce, since my employer sells merchandise on the web, but I'm down for anything.

Name: Jeffrey Sykes
UNI: js4452
git: kingsykes

[EDIT]: joebeut has joined me (see #22)

@jdebeer
@ozzieba
@njt2116
@jameslinjl
@cev2107
@ericdonahue

**Comment by joebeut** [comment]
Hey Jeffery!

I posted #22 and I'm interested in joining you. I'm all for ecommerce or anything consumer facing. Want to join up?

Shoot me an email at jtb2133@columbia.edu. 

Best,
Joe

**Comment by kingsykes** [comment]
Sounds good Joe!
- Jeffrey

**Comment by levbrie** [comment]
What is the status of this team?  I don't see your repo?

**Comment by kingsykes** [comment]
| UNI | Github username | Full Name |
| --- | --- | --- |
| abo2109 | andrewolo | Andrew Babatunde Olowude |
| cz2246 | cz2246 | Cem Zorlular |
| js4452 | kingsykes | Jeffrey Sykes |
| jtb2133 | joebeut | Joseph Thomas Beutler |
