### ISSUE TITLE
Style and Design Criteria

### ISSUE THREAD

**Issue by blanksblanks** [ColumbiaJS/js-course#23]
I just noticed the grading criteria in the wiki for our homework. I actually left quite a few comments to myself in my code notes wrt certain functions and in BallFollower.js I commented out a long alternative implementation that also passed the specs that I was keeping around for reference. I'm just wondering if I would be penalized for this. I don't know if hw1 has been graded yet, but I can still extract the extraneous comments and put them together with my class notes where they probably belong.

In the future, I'll keep these notes elsewhere for my own reference so that the code is clean and easier on the eye for the grader.

**Comment by levbrie** [comment]
@blanksblanks That grading criteria will only apply starting with hw2 so you don't have to worry about it in hw1.  In general, it is best to keep long commented out alternatives elsewhere.  If you want to write comments that provide usage examples or something like that (you can see examples of this in angular's material repo, for example: https://github.com/angular/material/blob/master/src/components/bottomSheet/bottomSheet.js) I would of course encourage it but it definitely isn't necessary  (I find code where the functions are short and their names self-explanatory tend to be far easier to follow than well-commented code with obscure function names).
