### ISSUE TITLE
mac book charger

### ISSUE THREAD

**Issue by kevin-mcdonald** [ColumbiaJS/js-course#27]
Hi,
I left my macbook charger in the CS lounge when I left the hackathon around 5:30 (it was still plugged into the wall by the kitchen.  Did anyone happen to grab it?
thanks,
Kevin

**Comment by njt2116** [comment]
Crap.  I saw it there and didn't grab it.  I think @williamFalcon was the last out of our group who was in the CS lounge..... Maybe he grabbed it? Sorry!!
