### ISSUE TITLE
Expected indentation errors

### ISSUE THREAD

**Issue by annie** [ColumbiaJS/js-course#34]
When I run gulp, I'm getting a bunch of errors for DI.spec.js (but only the one in di and not the one in di-simple) saying "Expected indentation of 11 characters" - any idea what's happening?  There was another issue about this but it was closed without an answer.

**Comment by jameslinjl** [comment]
If you go to line 71 and change the indentation to 6 spaces/characters, then the error should disappear.

**Comment by annie** [comment]
@jameslinjl Thank you!!
