### ISSUE TITLE
Load required modules of a module

### ISSUE THREAD

**Issue by blanksblanks** [ColumbiaJS/js-course#36]
I just posted this on an old issue, but that issue was closed so I'm posting it again here just in case.

I'm still having problems finding a way for my module to hold onto the reference of the other modules in its dependents. When you are in the spec file and you want to get the dependencies of dependencies, you're only given the dependencies as a string i.e. 'moduleA'. How can DI.js access moduleA var in the DI.spec.js when it is only given 'moduleA' as a string?

```
47        var moduleA = DI.module('moduleA', []),
48            moduleB = DI.module('moduleB', ['moduleA']);
```

**Comment by levbrie** [comment]
@blanksblanks DI.js needs to keep track of all of the modules that get created, preferably in a modules object.  In other words, if you create a module with:

``` js
DI.module('moduleA');
```

the DI object should have a modules object so that the structure of the DI.js file looks something like:

``` js
  module.exports = {
    modules: {},
    module: function (name, dependencies) {
      // your implementation of the module function here
    }
  };
```

when you call `DI.module('moduleA');` once you create moduleA, you want to add it to the modules object:

``` js
this.modules[nameOfModuleYouJustCreated] = moduleYouJustCreated;
```

That module itself will have to hold onto either an object or an array containing all of the modules it depends on, which it can use to look up the actual module itself from the modules object.  Does that make sense?

**Comment by blanksblanks** [comment]
It all makes sense, and that's what I tried doing up until this part, which I'm confused about:

"That module itself will have to hold onto either an object or an array containing all of the modules it depends on, which it can use to look up the actual module itself from the modules object."

Every time I refer to this.modules, for instance when I create a 'new DI(moduleB, [moduleA])' and search for my dependencies, I get 'this.modules[moduleA] = undefined', whether I'm looking at this.modules in the module function in exports, or inside the DI object itself.

I tried to console log the results, and this is what I get. I've been stuck on just these last two tests for the past three days, but I feel like they're the most important ones. Since the deadline is extended, I'm going to try to come to your office hours to check it out. If you can glean what I'm doing wrong from here and give me a hint in the right direction, that would help a lot!

```
      1) should load the required modules of a module
module function in exports getting called for arguments { '0': 'moduleA', '1': [] }
this.module[] undefined
creating new DI object... moduleA []
this.modules[moduleA]= { name: 'moduleA',
  dependencies: [],
  register: [Function: register],
  inject: [Function: inject],
  getRegisteredFunc: [Function: getRegisteredFunc] }
module function in exports getting called for arguments { '0': 'moduleB', '1': [ 'moduleA' ] }
this.module[moduleA] undefined
creating new DI object... moduleB [ 'moduleA' ]
this.modules[moduleB]= { name: 'moduleB',
  dependencies: [ 'moduleA' ],
  register: [Function: register],
  inject: [Function: inject],
  getRegisteredFunc: [Function: getRegisteredFunc] }
module function in exports getting called for arguments { '0': 'moduleC', '1': [ 'moduleB' ] }
this.module[moduleB] undefined
creating new DI object... moduleC [ 'moduleB' ]
this.modules[moduleC]= { name: 'moduleC',
  dependencies: [ 'moduleB' ],
  register: [Function: register],
  inject: [Function: inject],
  getRegisteredFunc: [Function: getRegisteredFunc] }
logging from within DI object...
dependencies []
this.modules undefined
logging from within DI object...
dependencies [ 'moduleA' ]
this.modules undefined
logging from within DI object...
dependencies [ 'moduleA' ]
this.modules undefined
logging from within DI object...
dependencies [ 'moduleB' ]
this.modules undefined
```

**Comment by levbrie** [comment]
@blanksblanks Hey Nina, will you push your latest code so I can take a look at the current version?

**Comment by blanksblanks** [comment]
Hey Lev, it should be the current version, littered with console log
statements. The dictionary of modules shouldn't be a global variable right?

[EDIT: I clicked too hastily on that email. I just pushed the latest code so now it should the latest version. (2:50pm) ]

On Feb 24, 2015, at 1:44 PM, Lev Brie notifications@github.com wrote:

@blanksblanks https://github.com/blanksblanks Hey Nina, will you push
your latest code so I can take a look at the current version?

**Comment by levbrie** [comment]
@blanksblanks Got it, let me try to answer your question generally here and then send an email regarding your actual code afterwards.  In the first place, I think you want to be very careful not to confuse the three major pieces of this Dependency Injection system.  The first, which is represented by the object that you are exporting, is meant to be the DI object.  The DI object has only 2 responsibilities:
1. It has a `modules` object that stores all of the modules in the entire system.
2. It has a `module` method that is responsible for either fetching modules (when we use `DI.module('moduleName')` without a second parameter, or for creating modules (when we pass an array of dependencies as the second parameter).

The modules object itself should be very simple.  If you create your DI object with:

``` js
module.exports = {
    modules: {},
    module: function (name, dependencies) {
      // your module getter and creator code here
    }
};
```

then, given a module 'app' that you've created and stored in an app variable, from inside your `module` function you should be able to add that created module to the modules object using:

``` js
this.modules['app'] = app;
```

If you want to pass in the name from a `name` variable and add a `someModule` module you can of course use:

``` js
this.modules[name] = someModule;
```

to retrieve this module you can then use:

``` js
var moduleToGet = this.modules[name];
```

If you are inside of a function nested inside of the module function, that function will no longer have the same `this` value, so you can create a reference to `this` using `self`: `var self = this;` and then use self from inside the nested function.  Let me know if this helps clear things up.

Best,
Lev

**Comment by blanksblanks** [comment]
Turns out I was adding the module to the modules object, but it wasn't being properly retrieved. I finally figured it out, thank you for the clarification!

**Comment by levbrie** [comment]
Awesome!
