### ISSUE TITLE
Due Date Hwk1

### ISSUE THREAD

**Issue by njt2116** [ColumbiaJS/js-course#4]
The due date for this homework on the README.md is listed as **"Wed Jan 21st at 11:59pm."**  I believe the course email says it should be due **Wed Jan 28th at 11:59pm**.

**Comment by njt2116** [comment]
Also, how do you add a label to an issue? Wanted to add **"Question"** but I can't seem to figure it out.

**Comment by levbrie** [comment]
@njt2116 The homework should indeed be Jan 28. Thanks for pointing this out. Having it due several days before I sent it out would have made it real tough to get it done on time. 

I've just fixed this in the README.  

As for Labels, there should be a Labels button you can click on in the sidebar:

<img src="https://cloud.githubusercontent.com/assets/1441307/5893373/4f4bfeae-a4af-11e4-8efe-67abee926f6f.png" alt="alt text" width="200">

---

which will bring up a list of labels to attach to an issue (I've attached question to this one).

---

<img src="https://cloud.githubusercontent.com/assets/1441307/5893374/5913023e-a4af-11e4-9212-1bf17371d9c5.png" alt="alt text" width="300">
You can also create new labels by going to the main issues page, clicking on labels,

---

<img src="https://cloud.githubusercontent.com/assets/1441307/5893375/591a0ab6-a4af-11e4-80cc-9a87b0d7eedd.png" alt="alt text" width="500">

 and then clicking new labels.

---

<img src="https://cloud.githubusercontent.com/assets/1441307/5893376/591b42dc-a4af-11e4-9ad0-9f7f15c99648.png" alt="alt text" width="500">

---
