### ISSUE TITLE
Note on The Setup page and npm install

### ISSUE THREAD

**Issue by blanksblanks** [ColumbiaJS/js-course#5]
It might be useful to add in the instructions that if you run into problems with <code>npm install</code> for any of the dependencies you can run <code>sudo chown -R $(whoami) ~/.npm</code> first instead of having to add <code>sudo</code> every time. Also this is a little trivial, but item 7 in the list has two instructions in it.

**Comment by levbrie** [comment]
@blanksblanks Yes, absolutely.  I've added a note to the setup docs (and it looks like I was missing a period after the 8 in my markdown, so the markdown parser just put it all on the same line. Great catch!).
