### ISSUE TITLE
whitespace errors

### ISSUE THREAD

**Issue by ghost** [ColumbiaJS/js-course#6]
I must be going nuts... is anybody else getting consistent whitespace errors?  This happens with my double-array and sum-array as you might imagine.

**Comment by jameslinjl** [comment]
I was getting them for a little while. Have you removed whitespace in accordance with the style guide enforcer?

**Comment by annie** [comment]
Are you getting "mixed tabs and spaces" errors?  That happened to me a lot too, I just had to change some settings on my text editor

**Comment by ghost** [comment]
Yeah... doesn't like tabs.  I was using 'vi.'  whoops...  4 spaces using the spacebar.  Thanks everyone.

**Comment by annie** [comment]
You can change your vi settings so that a tab is translated to 4 spaces!  Manually typing the spaces gets pretty annoying haha
