### ISSUE TITLE
HW2?

### ISSUE THREAD

**Issue by kristiehoward** [ColumbiaJS/js-course#7]
Any word on when HW2 will be out? If it is due on Wed it would be great to get it before the weekend starts (in general) so that assignments don't pile up during the week!

**Comment by ghost** [comment]
Gotta agree here. Also any details on the project due in March?

**Comment by levbrie** [comment]
@kbh2120 Kristie, that's a very good point.  I'll make sure to always give you a full weekend on homeworks.  And @cev2107 details on the project should be out tonight!
